In [ ]:
# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Fmou4Ou0EDyp2kewb9tZ3dUCINImaiQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading data from dataset
df=pd.read_csv("Final Test File.csv")
df.shape
df.head(10)

#Selecting rows on specific condition
ddf=df[df['Vintage']>200]
ddf.shape

#Sorting the values based on Vintage column
df.sort_values(by=['Vintage'])

#Grouping the dataset based on Region_Code
g=df.groupby('Region_Code')
for Region_Code,i in g:
  print(Region_Code)
  print(i)
sg=g.get_group(3)
sg 

# Calculation Of Mean in each Group
s=df.groupby('Region_Code').mean()

#Adding a new column to existing dataset
df['Annual_Premium']=s['Policy_Sales_Channel']
df.head(10)


#Pickling of dataframe

df.to_pickle('Vehicle_Insurance.pkl')

#Reading pickle file 
newdf=pd.read_pickle('Vehicle_Insurance.pkl')
newdf.head()

#Scatter plot with labeled axis

x=df['id'].to_list()
y=df['Vintage'].to_list()
plt.scatter(x,y, color='green')
plt.xlabel('Id')
plt.ylabel("Vintage")
plt.show

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""

0
      id Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
181  182   Male   52  ...                   124       89         0
185  186   Male   52  ...                    26      134         0
232  233   Male   53  ...                    26       69         0

[3 rows x 12 columns]
2
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
98    99  Female   21  ...                   152       79         0
214  215    Male   44  ...                    26      265         0
448  449  Female   23  ...                   152      247         0
464  465    Male   24  ...                   152      224         0
482  483  Female   25  ...                   152      113         0

[5 rows x 12 columns]
3
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
1      2    Male   76  ...                    26      183         0
8      9  Female   24  ...                   152       28         0
49    50    Male   48  ...                   124      246         0
52    53  Female   49  ...                   152      130         0
59    60    Male   29  ...                   152      165         0
101  102    Male   24  ...                   152       52         0
120  121    Male   39  ...                    26      216         1
144  145    Male   21  ...                   160      212         0
160  161    Male   20  ...                   160      206         0
197  198    Male   42  ...                   124      105         1
238  239    Male   33  ...                   152      255         0
241  242    Male   27  ...                   152      125         0
292  293  Female   43  ...                    26       59         1

[13 rows x 12 columns]
5
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
83    84  Female   39  ...                    26      141         0
319  320    Male   43  ...                   124      178         0

[2 rows x 12 columns]
6
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
9     10  Female   32  ...                   152       80         0
15    16    Male   37  ...                   156      147         1
27    28    Male   26  ...                   152       57         0
207  208  Female   21  ...                   152       40         0
208  209    Male   24  ...                   151      245         0
272  273  Female   60  ...                   157      143         0
293  294  Female   28  ...                   152      215         0
316  317    Male   54  ...                   124       93         0
410  411    Male   28  ...                   124      282         0
413  414  Female   24  ...                   152      168         0
421  422    Male   23  ...                   152      256         0

[11 rows x 12 columns]
7
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
99   100  Female   24  ...                   160       68         0
468  469    Male   70  ...                   124      213         0
481  482  Female   33  ...                    26      103         0

[3 rows x 12 columns]
8
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
28    29  Female   25  ...                   152      223         0
30    31  Female   26  ...                   160      136         0
36    37    Male   71  ...                    19      253         0
38    39    Male   45  ...                   124      264         0
60    61    Male   49  ...                   156       30         0
82    83  Female   39  ...                   152      131         0
103  104  Female   22  ...                   152      156         0
110  111    Male   27  ...                   122       77         0
134  135  Female   27  ...                   152      260         0
150  151    Male   25  ...                   152      206         0
167  168  Female   26  ...                   152      101         0
169  170  Female   28  ...                   152       86         0
186  187    Male   48  ...                   124      135         0
190  191  Female   28  ...                   152       30         0
203  204    Male   42  ...                   154       66         0
226  227    Male   37  ...                   152      194         0
270  271    Male   62  ...                    26      194         0
289  290    Male   64  ...                   124      293         0
297  298    Male   60  ...                   124       21         0
314  315    Male   42  ...                   124      213         0
317  318    Male   48  ...                   124      113         0
324  325    Male   24  ...                   152      231         0
334  335  Female   22  ...                   152      217         0
336  337    Male   21  ...                   160      278         0
338  339    Male   36  ...                    26      249         0
353  354    Male   20  ...                   160       79         0
361  362  Female   23  ...                   152      257         0
371  372  Female   25  ...                   152      213         0
383  384  Female   24  ...                   152       86         0
384  385    Male   26  ...                   152       81         0
395  396    Male   75  ...                    26       11         0
420  421  Female   26  ...                   152      181         0
424  425  Female   21  ...                   152       99         0
430  431    Male   48  ...                   124      247         1
436  437    Male   29  ...                   124      241         0
439  440  Female   49  ...                   124      197         0
455  456    Male   49  ...                   124       98         0
459  460    Male   40  ...                   152      165         0
466  467    Male   70  ...                    26      249         0
473  474  Female   24  ...                   152      155         0
475  476    Male   59  ...                    26      134         0
484  485  Female   36  ...                    26      244         1
488  489    Male   72  ...                    26       61         0
495  496    Male   20  ...                   160      292         0

[44 rows x 12 columns]
9
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
215  216  Female   25  ...                   160      202         0

[1 rows x 12 columns]
10
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
274  275  Female   38  ...                   124      103         0
286  287    Male   24  ...                   152       45         0
288  289    Male   26  ...                   152       69         0
454  455  Female   27  ...                   152      152         0

[4 rows x 12 columns]
11
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
3      4    Male   21  ...                   152      203         0
6      7    Male   23  ...                   152      249         0
29    30    Male   57  ...                   157      232         1
71    72  Female   27  ...                    26       63         0
149  150  Female   22  ...                   152      258         0
189  190  Female   27  ...                   124      254         0
202  203    Male   22  ...                   152      272         0
245  246  Female   21  ...                   152      242         1
249  250    Male   41  ...                    26      152         0
265  266  Female   22  ...                   152      117         0
304  305    Male   24  ...                   152      233         0
379  380    Male   25  ...                   152      132         0
431  432    Male   42  ...                   124       46         0
458  459    Male   33  ...                   152      271         0

[14 rows x 12 columns]
12
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
251  252    Male   23  ...                    26      111         0
261  262  Female   22  ...                   152      128         0
315  316    Male   20  ...                   160       49         0
367  368  Female   20  ...                   160      203         0

[4 rows x 12 columns]
13
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
122  123    Male   37  ...                   124      293         0
254  255    Male   21  ...                   152       30         0
259  260    Male   24  ...                   152      207         0
291  292  Female   22  ...                   152       66         0
294  295    Male   22  ...                   152      104         0
389  390    Male   21  ...                   152       70         0
425  426  Female   24  ...                   151       19         0

[7 rows x 12 columns]
14
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
282  283  Female   21  ...                   152       56         0
437  438  Female   28  ...                   152      258         0

[2 rows x 12 columns]
15
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
12    13  Female   41  ...                    14      221         0
24    25    Male   34  ...                   152      180         0
46    47  Female   29  ...                   152       34         0
48    49  Female   25  ...                   152       12         0
64    65    Male   39  ...                   124       22         0
94    95  Female   23  ...                   152      209         0
124  125    Male   23  ...                   160      256         0
159  160  Female   31  ...                   152       84         0
182  183    Male   47  ...                    14       99         0
196  197  Female   56  ...                   154      229         0
218  219    Male   22  ...                   160      100         0
233  234    Male   62  ...                    86      239         0
237  238    Male   28  ...                   152      245         0
276  277  Female   36  ...                    26       69         1
285  286    Male   42  ...                    26       66         0
305  306    Male   24  ...                   152      143         0
340  341    Male   27  ...                   152      260         0
359  360    Male   54  ...                   124      171         1
398  399  Female   47  ...                    14      166         0
434  435    Male   76  ...                    14      126         0
449  450    Male   33  ...                   152      190         0

[21 rows x 12 columns]
16
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
51    52    Male   22  ...                   152      216         0
191  192  Female   24  ...                   152      284         0
295  296  Female   26  ...                   152      238         0
433  434    Male   25  ...                   152      178         0

[4 rows x 12 columns]
17
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
85    86  Female   21  ...                   160      243         0
273  274  Female   20  ...                   156      181         0

[2 rows x 12 columns]
18
      id Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
123  124   Male   34  ...                   124      156         1
337  338   Male   23  ...                    26       16         0
491  492   Male   43  ...                   124      268         0

[3 rows x 12 columns]
19
      id Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
63    64   Male   58  ...                    26      141         0
152  153   Male   51  ...                   124      228         0

[2 rows x 12 columns]
20
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
128  129  Female   22  ...                   152      219         0
221  222    Male   40  ...                    26      204         0

[2 rows x 12 columns]
21
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
267  268  Female   28  ...                   152       95         0
299  300    Male   22  ...                   152       29         0
416  417    Male   41  ...                   157       87         1
451  452  Female   23  ...                   152      270         0

[4 rows x 12 columns]
22
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
154  155  Female   24  ...                   152      125         0

[1 rows x 12 columns]
23
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
74    75    Male   59  ...                   124       39         0
87    88    Male   25  ...                   152       58         0
443  444  Female   25  ...                   152      228         0

[3 rows x 12 columns]
24
      id Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
366  367   Male   31  ...                   156      257         0

[1 rows x 12 columns]
25
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
119  120  Female   23  ...                   152      149         0
127  128  Female   22  ...                   160       22         0
161  162    Male   70  ...                   124      230         0
343  344    Male   25  ...                   152      275         0

[4 rows x 12 columns]
26
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
47    48    Male   51  ...                    22       83         0
75    76  Female   59  ...                   122      136         0
80    81    Male   54  ...                    22       74         0
198  199  Female   26  ...                   152      142         0

[4 rows x 12 columns]
27
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
117  118  Female   32  ...                   151      295         0
222  223    Male   21  ...                   160      106         0
248  249  Female   25  ...                   152      167         0
376  377    Male   23  ...                   160      199         0
476  477  Female   23  ...                   151       19         0

[5 rows x 12 columns]
28
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0      1    Male   44  ...                    26      217         1
2      3    Male   47  ...                    26       27         1
7      8  Female   56  ...                    26       72         1
13    14    Male   76  ...                    13       15         0
14    15    Male   71  ...                    30       58         0
..   ...     ...  ...  ...                   ...      ...       ...
487  488  Female   24  ...                   152      108         0
489  490  Female   39  ...                   154       59         1
490  491  Female   62  ...                   124      105         0
493  494  Female   20  ...                   160      120         0
497  498    Male   56  ...                    26      183         0

[145 rows x 12 columns]
29
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
107  108    Male   31  ...                   124      247         0
118  119  Female   23  ...                   152       23         0
139  140    Male   21  ...                   152      116         0
300  301    Male   21  ...                   152      258         0
320  321  Female   40  ...                   157       77         0
335  336    Male   20  ...                   157      271         0
344  345  Female   21  ...                   152      278         0
350  351    Male   46  ...                   124       64         0
374  375  Female   38  ...                   122      169         0
393  394  Female   49  ...                   156      265         0
441  442  Female   67  ...                   124       30         1
480  481    Male   73  ...                     3      132         0

[12 rows x 12 columns]
30
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
34    35  Female   32  ...                   152      169         0
40    41    Male   30  ...                   124       45         0
44    45  Female   26  ...                   152      186         0
65    66  Female   59  ...                    26      147         0
91    92  Female   26  ...                   152      189         0
95    96  Female   23  ...                   152      254         0
102  103  Female   20  ...                   160       78         0
112  113  Female   33  ...                   152      181         0
113  114    Male   50  ...                    26      229         1
114  115  Female   28  ...                   152      275         0
146  147  Female   27  ...                   152      246         0
165  166    Male   25  ...                   152       22         0
195  196    Male   55  ...                    26      226         0
205  206    Male   21  ...                   160       64         0
262  263    Male   45  ...                    26      121         0
307  308  Female   24  ...                   152      149         0
327  328    Male   26  ...                   152      270         0
352  353  Female   22  ...                   152      107         0
368  369    Male   52  ...                     1      152         0
408  409  Female   68  ...                   160      218         0
444  445  Female   21  ...                   152       82         0

[21 rows x 12 columns]
31
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
230  231    Male   42  ...                   124      181         0
250  251    Male   33  ...                   152      259         0
275  276  Female   52  ...                    26      127         0
298  299  Female   49  ...                   124       32         1
381  382    Male   66  ...                    26       90         0
394  395    Male   50  ...                   124      237         0

[6 rows x 12 columns]
32
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
447  448  Female   24  ...                   152      107         0

[1 rows x 12 columns]
33
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
5      6  Female   24  ...                   160      176         0
19    20  Female   60  ...                   124      102         1
77    78  Female   27  ...                   152      111         0
236  237  Female   48  ...                   154      132         0
303  304  Female   24  ...                   152      270         0
325  326  Female   24  ...                   152       45         0
402  403  Female   27  ...                   152      125         0
442  443    Male   54  ...                   124      295         0
457  458    Male   46  ...                   124       77         0
465  466    Male   42  ...                   124      107         0

[10 rows x 12 columns]
34
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
252  253  Female   20  ...                   160      281         0
428  429  Female   21  ...                   163       86         1

[2 rows x 12 columns]
35
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
10    11  Female   47  ...                   124       46         1
17    18  Female   25  ...                   152      299         0
43    44  Female   38  ...                   152      153         0
88    89  Female   23  ...                   160      114         0
109  110    Male   45  ...                   124      275         0
157  158    Male   41  ...                   154      221         0
174  175    Male   24  ...                   152       98         0
278  279  Female   20  ...                   160      214         0
309  310    Male   26  ...                   152      165         0
378  379    Male   20  ...                   160       81         0
407  408  Female   45  ...                    26      200         0
446  447    Male   54  ...                    26      113         1
462  463    Male   23  ...                   152      128         0
496  497    Male   22  ...                   152       84         0

[14 rows x 12 columns]
36
      id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response